name: Automatically creates a weekly agenda from an issue template
# on:
#   schedule:
#     - cron: '0 0 * * 3'
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
